Repository IQEngine/IQEngine, pull requests merged in 2023-07, with the labels that each got.

#290 Max pooling
  client/src/pages/spectrogram/SpectrogramPage.tsx
  client/src/utils/selector.ts
  package-lock.json
Labels: enhancement

#294 Improve query
  api/handlers/metadata.py
Labels: chore, python

#295 Add geolocation query
  api/handlers/metadata.py
Labels: enhancement, python

#297 Remove redux
  .gitignore
  api/handlers/metadata.py
  client/README.md
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/api/config/queries.test.tsx
  client/src/api/config/queries.ts
  client/src/api/datasource/BlobClient.ts
  client/src/api/datasource/DataSourceClient.ts
  client/src/api/datasource/DataSourceClientFactory.ts
  client/src/api/datasource/LocalClient.ts
  client/src/api/datasource/Queries.ts
  client/src/api/iqdata/ApiClient.ts
  client/src/api/iqdata/BlobClient.ts
  client/src/api/iqdata/IQDataClientFactory.ts
  client/src/api/iqdata/LocalClient.ts
  client/src/api/iqdata/Queries.ts
  client/src/api/metadata/BlobClient.ts
  client/src/api/metadata/LocalClient.ts
  client/src/api/metadata/MetadataClientFactory.ts
  client/src/api/metadata/Queries.ts
  client/src/api/metadata/__tests__/LocalClient.test.tsx
  client/src/api/user-settings/use-user-settings.tsx
  client/src/api/utils/AzureBlob.ts
  client/src/hooks/useIQEngineQueryClient.tsx
  client/src/index.tsx
  client/src/mocks/setupTests.tsx
  client/src/pages/repo-browser/AzureBlobBrowser.tsx
  client/src/pages/repo-browser/LocalFileBrowser.tsx
  client/src/pages/repo-browser/RepoBrowser.tsx
  client/src/pages/repo-browser/RepositoryAPITile.tsx
  client/src/pages/repo-browser/RepositoryTile.tsx
  client/src/pages/spectrogram/SpectrogramPage.tsx
  client/src/store/hooks.ts
  client/src/store/reducers/ConnectionReducer.ts
  client/src/store/reducers/LocalClientReducer.ts
  client/src/store/store.ts
  package-lock.json
Labels: chore

#298 Adding plugins container image
  .github/workflows/docker-pre-release.yml
  .github/workflows/docker-release.yml
Labels: enhancement

#300 Fix plugin requiring parameters to run
  client/src/pages/spectrogram/components/PluginsPane.tsx
  client/src/pages/spectrogram/hooks/useGetPluginsComponents.tsx
  plugins/src/wav_out/wav_out.py
Labels: bug

#301 enable null blob connection for public blob storage
  Makefile
  client/src/api/utils/AzureBlob.ts
  client/src/pages/repo-browser/RepositoryTile.tsx
  e2e/__tests__/confirm_estevez.spec.ts
  e2e/__tests__/confirm_gnuradio.spec.ts
Labels: feature

#303 Add capability to add and view comments.
  client/src/features/ui/auto-size-input/AutoSizeInput.tsx
  client/src/pages/spectrogram/components/annotation/AnnotationList.tsx
  client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.meta.json
  client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.tsx
Labels: enhancement

#306 add sticky sessions to infra
  infra/containerapp.bicep
  infra/iqengine.json
Labels: chore

#307 fix frequencies issue
  client/src/features/ui/auto-size-input/AutoSizeInput.tsx
  client/src/pages/spectrogram/components/annotation/AnnotationList.tsx
  client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.tsx
  client/src/utils/__tests__/rfFunctions.test.ts
  client/src/utils/rfFunctions.ts
Labels: bug

#299 cleaned up logo code
  client/src/features/ui/logo/Logo.tsx
Labels: chore

#296 Add initial changes for plugin spec
  api/handlers/datasources.py
  api/handlers/urlmapping.py
  client/package-lock.json
  client/src/api/config/queries.ts
  client/src/api/datasource/Queries.ts
  client/src/pages/spectrogram/Sidebar.tsx
  client/src/pages/spectrogram/SpectrogramPage.tsx
  client/src/pages/spectrogram/components/GlobalProperties/__tests__/GlobalProperties.test.tsx
  client/src/pages/spectrogram/components/PluginsPane.tsx
  client/src/pages/spectrogram/components/annotation/AnnotationList.tsx
  client/src/pages/spectrogram/components/metadata/MetaRaw.tsx
  client/src/pages/spectrogram/components/metadata/MetaViewer.tsx
  client/src/pages/spectrogram/components/metadata/__tests__/MetaRaw.test.tsx
  client/src/pages/spectrogram/components/metadata/__tests__/MetaViewer.test.tsx
  client/src/utils/sigmfMetadata.ts
  plugins/plugins_openapi.yaml
  plugins/src/models/plugins.py
  plugins/src/plugins_api.py
  plugins/src/requirements.txt
  plugins/src/samples.py
Labels: enhancement, feature

#314 fix manifest.json cors
  client/index.html
Labels: bug

#318 Fix sizing
  client/src/App.tsx
Labels: chore

#321 Add requirements.txt to dockerfile
  plugins/Dockerfile
  plugins/src/requirements.txt
Labels: chore

#323 fix annoying plugin bug
  client/src/pages/spectrogram/components/PluginsPane.tsx
  client/src/pages/spectrogram/hooks/useGetPluginsComponents.tsx
Labels: bug

#325 Fix settings key issue
  client/src/pages/spectrogram/SettingsPane.tsx
Labels: bug

#330 Create thumbnail image automatically
  .vscode/launch.json
  api/blob/__init__.py
  api/blob/azure_client.py
  api/database/database.py
  api/handlers/datasources.py
  api/handlers/iq.py
  api/handlers/metadata.py
  api/handlers/urlmapping.py
  api/helpers/__init__.py
  api/helpers/cipher.py
  api/helpers/urlmapping.py
  api/requirements.txt
  api/rf/__init__.py
  api/rf/samples.py
  api/rf/spectrogram.py
  api/tests/conftest.py
  api/tests/test_metadata.py
Labels: feature

#322 Add initial admin login
  README.md
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/authConfig.js
  client/src/hooks/useIQEngineProtectedRoute.tsx
  client/src/hooks/useIQEngineRouter.tsx
  client/src/index.tsx
  client/src/pages/admin/Admin.tsx
Labels: feature

#335 Add metadata refactor
  .github/workflows/linter.yml
  .mega-linter.yml
  Makefile
  api/database/database.py
  api/database/datasource_repo.py
  api/database/metadata_repo.py
  api/handlers/datasources.py
  api/handlers/iq.py
  api/handlers/metadata.py
  api/handlers/status.py
  api/tests/test_metadata.py
  api/tests/test_query_api.py
Labels: chore

#339 Query API datetime fix
  api/handlers/metadata.py
Labels: bug, python

#344 Async Azure Blob API implementation
  Dockerfile
  api/blob/azure_client.py
  api/handlers/datasources.py
  api/handlers/iq.py
  api/handlers/metadata.py
  api/requirements.txt
  api/tests/test_iq_api.py
Labels: feature

#343 Add initial admin page
  client/package-lock.json
  client/src/hooks/useIQEngineRouter.tsx
  client/src/pages/admin/Admin.tsx
  client/src/pages/admin/__tests__/admin.test.tsx
  client/src/pages/admin/admin.tsx
  client/src/pages/admin/pages/__tests__/configuration.test.tsx
  client/src/pages/admin/pages/__tests__/data-sources.test.tsx
  client/src/pages/admin/pages/__tests__/plugins.test.tsx
  client/src/pages/admin/pages/__tests__/users.test.tsx
  client/src/pages/admin/pages/configuration.tsx
  client/src/pages/admin/pages/data-sources.tsx
  client/src/pages/admin/pages/plugins.tsx
  client/src/pages/admin/pages/users.tsx
  client/src/pages/spectrogram/SettingsPane.tsx
Labels: feature

#349 new linting image
  Makefile
Labels: chore

#353 Make names better
  .github/workflows/run_api_tests.yml
Labels: chore

#352 Listing Datasources
  client/src/api/Models.ts
  client/src/api/datasource/__tests__/ApiClient.test.tsx
  client/src/api/datasource/api-client.ts
  client/src/api/datasource/blob-client.ts
  client/src/api/datasource/datasource-client-factory.ts
  client/src/api/datasource/datasource-client.ts
  client/src/api/datasource/hooks/use-get-datasources.tsx
  client/src/api/datasource/local-client.ts
  client/src/api/datasource/queries.ts
  client/src/pages/admin/admin.tsx
  client/src/pages/admin/pages/__tests__/data-sources.test.tsx
  client/src/pages/admin/pages/data-sources.tsx
  client/src/pages/repo-browser/LocalFileBrowser.tsx
  client/src/pages/repo-browser/RepoBrowser.tsx
Labels: feature

#354 add feature flags to config
  client/src/pages/admin/pages/__tests__/configuration.test.tsx
  client/src/pages/admin/pages/configuration.tsx
Labels: enhancement

#351 Add satdump to plugin image
  plugins/Dockerfile
Labels: feature

#357 Annotation pie chart
  api/handlers/metadata.py
  client/src/api/iqdata/__tests__/Queries.test.tsx
  client/src/api/metadata/__tests__/ApiClient.test.tsx
  client/src/api/metadata/__tests__/LocalClient.test.tsx
  client/src/pages/recordings-browser/AnnotationModal.tsx
  client/src/pages/recordings-browser/File.tsx
  client/src/pages/spectrogram/components/annotation/AnnotationList.tsx
  client/src/pages/spectrogram/components/annotation/AnnotationViewer.tsx
  client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.meta.json
  client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.tsx
  client/src/pages/spectrogram/components/metadata/__tests__/MetaRaw.test.tsx
  client/src/utils/__tests__/sigmfMetadata.test.ts
  client/src/utils/__tests__/validators.test.annotations.json
  client/src/utils/__tests__/validators.test.meta.json
  client/src/utils/constants.ts
  client/src/utils/parseMeta.ts
  client/src/utils/plotlyTemplate.ts
  client/src/utils/sigmfMetadata.ts
  plugins/src/azure_functions/SpectrogramThumbnails/__init__.py
  plugins/src/markos_detector/markos_detector.py
  plugins/src/simple_detector/simple_detector.py
  plugins/src/template_plugin/template_plugin.py
Labels: feature

#348 Selection cursor updates
  client/src/pages/spectrogram/FreqSelector.tsx
  client/src/pages/spectrogram/SettingsPane.tsx
  client/src/pages/spectrogram/Sidebar.tsx
  client/src/pages/spectrogram/SpectrogramPage.tsx
  client/src/pages/spectrogram/TimeSelector.tsx
  client/src/pages/spectrogram/TimeSelectorMinimap.tsx
  client/src/utils/rfFunctions.ts
Labels: feature

#363 add configuration not updating correctly fix
  client/src/api/config/queries.ts
  client/src/pages/admin/pages/configuration.tsx
Labels: bug

#356 Upload to triage container page
  api/database/models.py
  api/handlers/config.py
  api/tests/test_api.py
  client/src/api/config/queries.ts
  client/src/hooks/use-router.tsx
  client/src/pages/UploadPage.tsx
  client/src/pages/repo-browser/LocalFileBrowser.tsx
  client/src/utils/FetchMoreDataSource.ts
Labels: feature

#365 add use get image hook
  client/package-lock.json
  client/package.json
  client/src/pages/spectrogram/hooks/__tests__/use-get-image.test.tsx
  client/src/pages/spectrogram/hooks/use-get-image.tsx
  client/src/utils/testFunctions.ts
  client/vite.config.ts
  client/vitest.setup.ts
Labels: enhancement, javascript

#369 Admin page - add data source
  .cspell.json
  api/handlers/datasources.py
  client/src/api/datasource/queries.ts
  client/src/hooks/use-router.tsx
  client/src/pages/admin/pages/__tests__/add-data-source.test.tsx
  client/src/pages/admin/pages/add-data-source.tsx
  client/src/pages/admin/pages/data-sources.tsx
Labels: enhancement, feature

#370 Create IQEngine meta query page
  client/index.html
  client/package-lock.json
  client/package.json
  client/public/pin.png
  client/src/App.tsx
  client/src/api/metadata/ApiClient.ts
  client/src/api/metadata/Queries.ts
  client/src/hooks/use-router.tsx
  client/src/mocks/setup-tests.tsx
  client/src/pages/metadata-query/__tests__/band-selection.test.tsx
  client/src/pages/metadata-query/__tests__/band.test.tsx
  client/src/pages/metadata-query/__tests__/date-query.test.tsx
  client/src/pages/metadata-query/__tests__/freq-query.test.tsx
  client/src/pages/metadata-query/__tests__/geo-query-type.test.tsx
  client/src/pages/metadata-query/__tests__/geo-query-types.test.tsx
  client/src/pages/metadata-query/__tests__/queries.test.tsx
  client/src/pages/metadata-query/__tests__/results.test.tsx
  client/src/pages/metadata-query/__tests__/string-query.test.tsx
  client/src/pages/metadata-query/band-selection.tsx
  client/src/pages/metadata-query/band.tsx
  client/src/pages/metadata-query/date-query.tsx
  client/src/pages/metadata-query/freq-query.tsx
  client/src/pages/metadata-query/geo-query-type.tsx
  client/src/pages/metadata-query/geo-query-types.tsx
  client/src/pages/metadata-query/geo-query.tsx
  client/src/pages/metadata-query/metadata-query.tsx
  client/src/pages/metadata-query/queries.ts
  client/src/pages/metadata-query/results.tsx
  client/src/pages/metadata-query/string-query.tsx
  client/src/pages/recordings-browser/File.tsx
Labels: feature

#362 Admin page - Adding pluginEndpoint
  api/handlers/plugins.py
  client/package-lock.json
  client/package.json
  client/src/api/Models.ts
  client/src/api/plugin/Queries.tsx
  client/src/api/plugin/__tests__/queries.test.tsx
  client/src/api/plugin/queries.tsx
  client/src/mocks/setup-tests.tsx
  client/src/pages/admin/pages/__tests__/add-data-source.test.tsx
  client/src/pages/admin/pages/__tests__/configuration.test.tsx
  client/src/pages/admin/pages/__tests__/plugins.test.tsx
  client/src/pages/admin/pages/plugins.tsx
  client/src/pages/spectrogram/components/PluginsPane.tsx
  client/src/pages/spectrogram/components/metadata/__tests__/MetaRaw.test.tsx
  client/src/pages/spectrogram/hooks/use-get-plugins-components.tsx
Labels: feature

#374 Rename files
  client/src/hooks/use-router.tsx
  client/src/pages/sigmf.tsx
  client/src/pages/spectrogram/InfoPane.tsx
  client/src/pages/spectrogram/freq-selector.tsx
  client/src/pages/spectrogram/ruler-side.tsx
  client/src/pages/spectrogram/ruler-top.tsx
  client/src/pages/spectrogram/scroll-bar.tsx
  client/src/pages/spectrogram/settings-pane.tsx
  client/src/pages/spectrogram/sidebar.tsx
  client/src/pages/spectrogram/spectrogram-page.tsx
  client/src/pages/spectrogram/time-selector-minimap.tsx
  client/src/pages/spectrogram/time-selector.tsx
  client/src/pages/upload-page.tsx
Labels: chore

#375 1383 generate ffts
  client/src/pages/spectrogram/hooks/__tests__/use-get-image.test.tsx
  client/src/pages/spectrogram/hooks/use-get-image.tsx
  client/src/utils/selector.ts
  client/src/utils/test-functions.ts
Labels: feature, javascript

#379 Auto loading data source
  api/database/datasource_repo.py
  api/handlers/datasources.py
  api/importer/all.py
  api/importer/datasource.py
  api/tests/conftest.py
  api/tests/test_importer.py
Labels: feature

#378 Extract modal
  .cspell.json
  client/src/api/plugin/queries.tsx
  client/src/features/ui/modal/Modal.tsx
  client/src/features/ui/modal/__tests__/Modal.test.tsx
  client/src/hooks/use-router.tsx
  client/src/pages/admin/pages/__tests__/add-data-source.test.tsx
  client/src/pages/admin/pages/__tests__/plugins.test.tsx
  client/src/pages/admin/pages/add-data-source.tsx
  client/src/pages/admin/pages/data-sources.tsx
  client/src/pages/admin/pages/plugins.tsx
  client/src/pages/recordings-browser/File.tsx
  client/src/pages/recordings-browser/FileAnnotationData.tsx
  client/src/pages/spectrogram/components/annotation/Actions.tsx
  client/src/pages/spectrogram/components/annotation/__tests__/Actions.test.tsx
  client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.tsx
Labels: enhancement

#367 Basic API Authorization
  api/handlers/datasources.py
  api/handlers/iq.py
  api/handlers/metadata.py
  api/handlers/plugins.py
  api/helpers/authorization.py
  api/requirements.txt
  api/tests/conftest.py
  api/tests/readme.md
  api/tests/test_api.py
  api/tests/test_authorization.py
  api/tests/test_keys.json
  api/tests/test_query_api.py
  api/tests/test_rbac.py
Labels: feature, python

#380 Add sync
  api/blob/azure_client.py
  api/database/datasource_repo.py
  api/database/metadata_repo.py
  api/database/models.py
  api/handlers/datasources.py
  api/rf/samples.py
  api/tests/test_data.py
Labels: feature

#384 Enable Modal to change size
  client/src/features/ui/modal/Modal.tsx
  client/src/pages/recordings-browser/File.tsx
  client/src/pages/spectrogram/components/annotation/AnnotationList.tsx
Labels: chore

#388 Clean up aria labels
  client/src/features/ui/modal/Modal.tsx
  client/src/features/ui/modal/__tests__/Modal.test.tsx
  client/src/pages/admin/pages/__tests__/add-data-source.test.tsx
  client/src/pages/admin/pages/__tests__/configuration.test.tsx
  client/src/pages/admin/pages/add-data-source.tsx
  client/src/pages/admin/pages/configuration.tsx
  client/src/pages/spectrogram/components/annotation/Actions.tsx
  client/src/pages/spectrogram/components/annotation/__tests__/Actions.test.tsx
  client/src/pages/spectrogram/components/annotation/__tests__/AnnotationList.test.tsx
  client/src/pages/spectrogram/components/metadata/MetaRaw.tsx
  client/src/pages/spectrogram/components/metadata/__tests__/MetaRaw.test.tsx
Labels: chore

#389 Change api query return type
  api/handlers/metadata.py
  api/tests/test_data.py
  api/tests/test_query_api.py
Labels: python, Breaking Change

#391 New plugin base image
  .github/workflows/docker-plugin-base-image.yml
  plugins/Dockerfile-base-image
Labels: chore

#390 Track metadata api
  api/database/models.py
  api/handlers/metadata.py
  api/tests/test_api.py
  api/tests/test_data.py
Labels: feature, python

#387 Data type to bytes per sample cleanup and API change
  Makefile
  api/handlers/iq.py
  api/tests/test_iq_api.py
  client/src/api/iqdata/ApiClient.ts
  client/src/api/iqdata/BlobClient.ts
  client/src/api/iqdata/LocalClient.ts
  client/src/api/metadata/BlobClient.ts
  client/src/api/metadata/LocalClient.ts
  client/src/pages/spectrogram/components/PluginsPane.tsx
  client/src/utils/__tests__/sigmfMetadata.test.ts
  client/src/utils/parseMeta.ts
  client/src/utils/selector.ts
  client/src/utils/sigmfMetadata.ts
Labels: chore

#381 New data load
  client/src/api/iqdata/ApiClient.ts
  client/src/api/iqdata/BlobClient.ts
  client/src/api/iqdata/IQDataClient.ts
  client/src/api/iqdata/LocalClient.ts
  client/src/api/iqdata/Queries.ts
  client/src/api/metadata/Queries.ts
  client/src/mocks/setup-tests.tsx
  client/src/pages/spectrogram/hooks/__tests__/use-spectrogram.test.tsx
  client/src/pages/spectrogram/hooks/use-spectrogram.tsx
  client/src/utils/__tests__/group.test.ts
  client/src/utils/group.ts
Labels: feature

#395 Small cleanup
  client/src/api/iqdata/ApiClient.ts
  client/src/api/iqdata/BlobClient.ts
  client/src/api/iqdata/LocalClient.ts
  client/src/pages/spectrogram/spectrogram-page.tsx
  client/src/utils/fetch-more-data-source.ts
  client/src/utils/selector.ts
Labels: chore

#398 Correct sync
  api/blob/azure_client.py
  api/database/datasource_repo.py
  api/database/metadata_repo.py
  api/database/models.py
Labels: bug

#396 New recording view page
  client/src/hooks/use-feature-flags.tsx
  client/src/hooks/use-router.tsx
  client/src/pages/metadata-query/__tests__/results.test.tsx
  client/src/pages/recording-view/hooks/__tests__/use-get-image.test.tsx
  client/src/pages/recording-view/hooks/__tests__/use-spectrogram.test.tsx
  client/src/pages/recording-view/hooks/use-get-image.tsx
  client/src/pages/recording-view/hooks/use-spectrogram.tsx
  client/src/pages/recording-view/recording-view.tsx
  client/src/pages/recordings-browser/File.tsx
  client/src/pages/recordings-browser/RecordingsBrowser.tsx
Labels: chore

#399 Add datasource to query
  client/src/pages/metadata-query/__tests__/data-source-query.test.tsx
  client/src/pages/metadata-query/__tests__/queries.test.tsx
  client/src/pages/metadata-query/data-source-query.tsx
  client/src/pages/metadata-query/queries.ts
Labels: enhancement

#404 Datasource meta query
  api/handlers/metadata.py
  client/src/api/datasource/api-client.ts
  client/src/api/datasource/blob-client.ts
  client/src/api/datasource/datasource-client.ts
  client/src/api/datasource/local-client.ts
  client/src/api/datasource/queries.ts
  client/src/api/metadata/queries.ts
  client/src/pages/metadata-query/results.tsx
Labels: chore

#405 Moving tro context to avoid prop drilling
  client/src/api/iqdata/Queries.ts
  client/src/pages/recording-view/components/ruler-side.tsx
  client/src/pages/recording-view/components/ruler-top.tsx
  client/src/pages/recording-view/hooks/__tests__/use-spectrogram.test.tsx
  client/src/pages/recording-view/hooks/use-get-image.tsx
  client/src/pages/recording-view/hooks/use-spectrogram-context.tsx
  client/src/pages/recording-view/hooks/use-spectrogram.tsx
  client/src/pages/recording-view/recording-view.tsx
Labels: chore

#406 IQ Plot, Frequency Plot and Time plot Migrated to the new spectrogram page.
  client/src/pages/recording-view/components/frequency-plot.tsx
  client/src/pages/recording-view/components/iq-plot.tsx
  client/src/pages/recording-view/components/time-plot.tsx
  client/src/pages/recording-view/hooks/use-cursor-context.tsx
  client/src/pages/recording-view/recording-view.tsx
Labels: chore

#408 New sidebar
  client/src/pages/recording-view/components/plugins-pane.tsx
  client/src/pages/recording-view/components/settings-pane.tsx
  client/src/pages/recording-view/components/sidebar.tsx
  client/src/pages/recording-view/hooks/use-spectrogram-context.tsx
  client/src/pages/recording-view/recording-view.tsx
Labels: chore
