Repository IQEngine/IQEngine, pull requests merged in 2023-05, with the labels that each got.

#89 Docker labels and enabling push
  .github/workflows/docker-release.yml
  Dockerfile
Labels: chore

#90 Add permissions to push package
  .github/workflows/docker-release.yml
Labels: chore

#120 Add data to avoid pre-release conflicts
  .github/workflows/docker-pre-release.yml
  .github/workflows/docker-release.yml
Labels: chore

#122 Annotations table improvements
  .github/linters/.eslintrc.yml
  client/src/Components/DataTable/DataTable.tsx
  client/src/Components/Spectrogram/ScrollBar.jsx
  client/src/Components/Spectrogram/SpectrogramPage.jsx
  client/src/Utils/rfFunctions.ts
Labels: enhancement

#127 Add linters
  .pre-commit-config.yaml
Labels: chore

#131 Fix config error
  client/src/Config.ts
Labels: bug

#130 Add the initial edit view
  client/package-lock.json
  client/package.json
  client/src/Components/AutoSizeInput/AutoSizeInput.test.tsx
  client/src/Components/AutoSizeInput/AutoSizeInput.tsx
  client/src/Components/Button/Button.tsx
  client/src/Components/Collapsible/Collapsible.tsx
  client/src/Components/DataTable/DataTable.test.tsx
  client/src/Components/DataTable/DataTable.tsx
  client/src/Components/Spectrogram/RulerTop.jsx
  client/src/Components/Spectrogram/SpectrogramPage.jsx
  client/src/Utils/rfFunctions.test.ts
  client/src/Utils/rfFunctions.ts
  client/src/index.css
  client/src/services/data-sources.ts
  client/src/tailwind_index.css
Labels: feature

#135 Add react query support
  .cspell.json
  .github/linters/.cspell.json
  .github/workflows/docker-pre-release.yml
  .github/workflows/docker-release.yml
  .github/workflows/main_iqengineweb.yml
  .github/workflows/most_recent_pr_iqengineweb.yml
  README.md
  api/api.py
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/Components/RepoBrowser/RepoBrowser.jsx
  client/src/Components/Spectrogram/DetectorPane.jsx
  client/src/Config.test.ts
  client/src/Config.ts
  client/src/api/config/queries.test.tsx
  client/src/api/config/queries.ts
  client/src/api/datasource/queries.ts
  client/src/index.css
  client/src/index.tsx
  client/src/services/config.ts
  example.env
Labels: enhancement

#138 Add datasource api methods
  client/src/api/datasource/ApiClient.ts
  client/src/api/datasource/BlobClient.ts
  client/src/api/datasource/DataSourceClient.ts
  client/src/api/datasource/DataSourceClientFactory.ts
  client/src/api/datasource/LocalClient.ts
  client/src/api/datasource/Queries.ts
  client/src/api/datasource/queries.ts
Labels: feature

#142 Separate annotations out into it's own component
  client/src/Components/AutoSizeInput/AutoSizeInput.tsx
  client/src/Components/DataTable/DataTable.test.columns.json
  client/src/Components/DataTable/DataTable.test.rows.json
  client/src/Components/DataTable/DataTable.test.tsx
  client/src/Components/Spectrogram/SpectrogramPage.jsx
  client/src/Features/Annotations/Annotations.test.meta.json
  client/src/Features/Annotations/Annotations.test.tsx
  client/src/Features/Annotations/Annotations.tsx
  client/src/Utils/rfFunctions.test.ts
  client/src/Utils/rfFunctions.ts
  client/src/services/data-sources.ts
  client/vite.config.ts
Labels: enhancement

#144 Add types on the data source clients
  client/src/Utils/sigmfStructure.ts
  client/src/api/datasource/ApiClient.ts
  client/src/api/datasource/BlobClient.ts
  client/src/api/datasource/DataSourceClient.ts
  client/src/api/datasource/LocalClient.ts
Labels: chore

#147 Move to the new way to do Redux
  .github/linters/.markdown-link-check.json
  client/src/Components/RecordingsBrowser/Directory.jsx
  client/src/Components/RecordingsBrowser/File.tsx
  client/src/Components/RecordingsBrowser/RecordingsBrowser.jsx
  client/src/Components/RepoBrowser/AzureBlobBrowser.jsx
  client/src/Components/RepoBrowser/LocalFileBrowser.jsx
  client/src/Components/RepoBrowser/RepoBrowser.jsx
  client/src/Components/RepoBrowser/RepositoryTile.jsx
  client/src/Components/Spectrogram/AnnotationViewer.jsx
  client/src/Components/Spectrogram/DetectorPane.jsx
  client/src/Components/Spectrogram/FrequencyPlot.jsx
  client/src/Components/Spectrogram/IQPlot.jsx
  client/src/Components/Spectrogram/InfoPane.jsx
  client/src/Components/Spectrogram/RulerTop.jsx
  client/src/Components/Spectrogram/ScrollBar.jsx
  client/src/Components/Spectrogram/SettingsPane.jsx
  client/src/Components/Spectrogram/Sidebar.jsx
  client/src/Components/Spectrogram/SpectrogramPage.jsx
  client/src/Components/Spectrogram/TimePlot.jsx
  client/src/Constants/FetchMetaTypes.js
  client/src/Containers/RecordingsListContainer.js
  client/src/Containers/RepoBrowserContainer.js
  client/src/Containers/SpectrogramContainer.js
  client/src/Sources/FetchMetaSource.js
  client/src/Sources/FetchMoreDataSource.ts
  client/src/Sources/RecordingsListSource.js
  client/src/Store/Actions/BlobActions.js
  client/src/Store/Actions/BlobActions.ts
  client/src/Store/Actions/ConnectionActions.js
  client/src/Store/Actions/FetchMetaActions.js
  client/src/Store/Actions/FetchMetaActions.ts
  client/src/Store/Actions/MinimapActions.js
  client/src/Store/Actions/RecordingsListActions.js
  client/src/Store/Reducers/BlobReducer.js
  client/src/Store/Reducers/BlobReducer.ts
  client/src/Store/Reducers/ConnectionReducer.js
  client/src/Store/Reducers/ConnectionReducer.ts
  client/src/Store/Reducers/FetchMetaReducer.js
  client/src/Store/Reducers/FetchMetaReducer.ts
  client/src/Store/Reducers/MinimapReducer.js
  client/src/Store/Reducers/MinimapReducer.ts
  client/src/Store/Reducers/RecordingsListReducer.js
  client/src/Store/Reducers/RecordingsListReducer.ts
  client/src/Store/Reducers/rootReducer.js
  client/src/Store/hooks.ts
  client/src/Store/store.js
  client/src/Store/store.ts
  client/src/Utils/selector.ts
  client/src/index.tsx
  detectors/README.md
Labels: enhancement
