Repository IQEngine/IQEngine, pull requests merged in 2023-09, with the labels that each got.

#615 fix validation warnings
  client/src/utils/validators.ts
Labels: bug

#633 fix data loaded indicator
  client/src/pages/recording-view/components/scroll-bar.tsx
Labels: bug

#634 fix bug in the fix
  client/src/pages/recording-view/components/scroll-bar.tsx
Labels: bug

#637 Correct account key
  api/handlers/iq.py
Labels: bug

#639 Make the metadata properties shown on page smaller
  client/src/pages/recording-view/components/__tests__/meta-viewer.test.tsx
  client/src/pages/recording-view/components/meta-viewer.tsx
Labels: bug

#646 make tooltip contrast better
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Labels: bug

#648 Add aligment issue to annotation viewer
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Labels: bug

#650 Move no wrap to the paragraph
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Labels: bug

#652 giving feedback for plugin
  client/src/pages/recording-view/components/plugins-pane.tsx
Labels: enhancement

#653 Fix annotation viewer
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Labels: bug

#651 Truncate comment on spectrogram
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
  client/src/utils/__tests__/sigmfMetadata.test.ts
  client/src/utils/sigmfMetadata.ts
Labels: bug

#679 Add user name to sync for versions audit entry
  api/database/datasource_repo.py
  api/handlers/datasources.py
Labels: chore, python
