Repository IQEngine/IQEngine, pull requests merged in 2023-06, with the labels that each got.

#146 write load metadata script
  .cspell.json
  .gitignore
  .vscode/launch.json
  tools/metadata_loader/README.md
  tools/metadata_loader/__init__.py
  tools/metadata_loader/main.py
  tools/metadata_loader/requirements.txt
  tools/metadata_loader/requirements_tests.txt
  tools/metadata_loader/sample.env
  tools/metadata_loader/tests/__init__.py
  tools/metadata_loader/tests/test_unit_datasources.py
  tools/metadata_loader/tests/test_unit_metadata.py
Labels: feature

#152 Add sigMF schemas
  .pre-commit-config.yaml
  client/src/Components/Validator/SigMFSchema.ts
  client/src/Components/Validator/sigmf-adsb-ext-schema.json
  client/src/Components/Validator/sigmf-schema.json
  client/src/Store/Reducers/FetchMetaReducer.ts
Labels: enhancement

#154 Convert to daisy ui
  .github/linters/.stylelintrc.js
  .mega-linter.yml
  client/package-lock.json
  client/package.json
  client/src/Components/Admin/Users.tsx
  client/src/Components/Annotation/AnnotationList.tsx
  client/src/Components/AutoSizeInput/__tests__/AutoSizeInput.test.tsx
  client/src/Components/DataTable/DataTable.tsx
  client/src/Components/DualRangeSlider/DualRangeSlider.tsx
  client/src/Components/RecordingsBrowser/RecordingsBrowser.jsx
  client/src/Components/RepoBrowser/AzureBlobBrowser.jsx
  client/src/Components/RepoBrowser/LocalFileBrowser.jsx
  client/src/Components/RepoBrowser/RepoBrowser.jsx
  client/src/Components/RepoBrowser/RepositoryTile.jsx
  client/src/Components/RepoBrowser/SiggenTile.jsx
  client/src/Components/RepoBrowser/ValidatorTile.jsx
  client/src/Components/SignalGenerator/SignalGenerator.jsx
  client/src/Components/Spectrogram/DetectorPane.jsx
  client/src/Components/Spectrogram/InfoPane.jsx
  client/src/Components/Spectrogram/SettingsPane.jsx
  client/src/Components/Spectrogram/Sidebar.jsx
  client/src/Components/Spectrogram/SpectrogramPage.jsx
  client/src/Components/Styles/BootstrapStyle.tsx
  client/src/Components/Styles/TailwindStyle.tsx
  client/src/Components/Styles/ThemeSelector.tsx
  client/src/Components/Validator/SigMFSchema.ts
  client/src/Components/Validator/components/Playground.tsx
  client/src/Components/Validator/sigmf-schema.json
  client/src/Store/Reducers/FetchMetaReducer.ts
  client/src/index.css
  client/src/tailwind_index.css
  client/tailwind.config.js
  tests/main.py
Labels: enhancement

#155 Fix bug when working in nanosecond/picosecond
  client/src/Components/AutoSizeInput/AutoSizeInput.tsx
  client/src/Components/DataTable/DataTable.tsx
  client/src/Utils/rfFunctions.test.ts
  client/src/Utils/rfFunctions.ts
  client/src/index.css
Labels: bug

#161 Correct the validation of the first load
  client/src/Components/RepoBrowser/LocalFileBrowser.jsx
  client/src/Components/Spectrogram/SpectrogramPage.jsx
Labels: chore

#163 added playwright requirements to project
  .gitignore
  Makefile
  __tests__/example.spec.ts
  package-lock.json
  package.json
  playwright.config.ts
Labels: chore

#166 Fix query spelling
  client/src/api/metadata/Queries.ts
Labels: chore

#168 Remove tick
  client/src/Components/Spectrogram/SettingsPane.tsx
Labels: bug

#167 961 add tests
  .cspell.json
  Makefile
  __tests__/confirm_all_repos.spec.ts
  __tests__/confirm_gnuradio.spec.ts
  __tests__/example.spec.ts
  __tests__/trivial.spec.ts
  playwright.config.ts
Labels: chore

#170 add readme for tests, delete old test.
  __tests__/README.md
  client/public/vscode-pw-test-runner.png
  tests/README.md
  tests/main.py
  tests/requirements.txt
Labels: chore

#169 ApiClient upgrade to return SigmfMetaData and unit tests
  client/package-lock.json
  client/package.json
  client/src/api/datasource/__tests__/ApiClient.test.tsx
  client/src/api/metadata/ApiClient.ts
  client/src/api/metadata/__tests__/ApiClient.test.tsx
Labels: chore

#176 annotations-actions
  client/src/Components/Annotation/Actions.tsx
  client/src/Components/Annotation/AnnotationList.tsx
  client/src/Components/Annotation/__tests__/Actions.test.tsx
  client/src/Components/DataTable/__tests__/DataTable.test.tsx
  client/src/Components/RepoBrowser/RepositoryTile.tsx
  client/src/Components/Spectrogram/SpectrogramPage.tsx
Labels: enhancement

#181 Add Bicep deployment infra.
  infra/containerapp.bicep
  infra/environment.bicep
  infra/law.bicep
  infra/main.bicep
  infra/mongodb.bicep
Labels: enhancement

#184 Validator page
  client/package-lock.json
  client/package.json
  client/src/Components/Validator/FormData.ts
  client/src/Components/Validator/README.md
  client/src/Components/Validator/Validator.tsx
  client/src/Components/Validator/components/CopyLink.tsx
  client/src/Components/Validator/components/DemoFrame.tsx
  client/src/Components/Validator/components/Editors.tsx
  client/src/Components/Validator/components/ErrorBoundary.tsx
  client/src/Components/Validator/components/GeoPosition.tsx
  client/src/Components/Validator/components/Header.tsx
  client/src/Components/Validator/components/Playground.tsx
  client/src/Components/Validator/components/RawValidatorTest.tsx
  client/src/Components/Validator/components/SubthemeSelector.tsx
  client/src/Components/Validator/components/ThemeSelector.tsx
  client/src/Components/Validator/components/ValidatorSelector.tsx
  client/src/Components/Validator/components/index.ts
  client/src/Store/Actions/BlobActions.ts
  client/src/Store/Actions/FetchMetaActions.ts
  client/src/Utils/__tests__/validators.test.meta.json
  client/src/Utils/__tests__/validators.test.ts
  client/src/Utils/constants.ts
  client/src/Utils/sigmf-adsb-ext-schema.json
  client/src/Utils/sigmf-schema.json
  client/src/Utils/validators.ts
Labels: bug, enhancement

#188 Fix annotation not updating
  client/src/Components/Annotation/Actions.tsx
  client/src/Components/Annotation/AnnotationList.tsx
  client/src/Components/Annotation/__tests__/Actions.test.tsx
  client/src/Components/Annotation/__tests__/AnnotationList.test.tsx
Labels: bug

#175 Fix local files
  client/src/Components/RepoBrowser/LocalFileBrowser.tsx
  client/src/api/datasource/LocalClient.ts
  client/src/api/iqdata/LocalClient.ts
  client/src/api/metadata/LocalClient.ts
  client/src/api/metadata/__tests__/LocalClient.test.tsx
Labels: bug

#187 Ignore compiled files for bicep and add deploy to azure button
  .gitignore
  Makefile
  README.md
  infra/iqengine.json
  infra/main.bicep
Labels: enhancement

#190 Handle top bug fix
  client/src/Components/Spectrogram/SpectrogramPage.tsx
Labels: bug

#191 Add metaviewer fix and prettier config fix
  .vscode/settings.json
  client/src/Components/MetaViewer/MetaViewer.tsx
  e2e/README.md
Labels: bug

#192 Fix timing auto size bug
  client/src/Components/AutoSizeInput/AutoSizeInput.tsx
Labels: bug

#197 Renamed detector to plugin and migrated towards the new plugins API
  .github/workflows/docker-pre-release.yml
  .github/workflows/docker-release.yml
  .github/workflows/main_iqengineweb.yml
  .github/workflows/most_recent_pr_iqengineweb.ymlDISABLED
  .gitignore
  .vscode/settings.json
  Makefile
  README.md
  api/handlers/config.py
  api/tests/test_api.py
  client/src/Components/Admin/Plugins.tsx
  client/src/Components/Spectrogram/DetectorPane.tsx
  client/src/Components/Spectrogram/PluginsPane.tsx
  client/src/Components/Spectrogram/Sidebar.tsx
  client/src/Components/Spectrogram/SpectrogramPage.tsx
  client/src/Utils/selector.ts
  client/src/api/config/queries.test.tsx
  client/src/api/config/queries.ts
  detectors/README.md
  detectors/azure_functions/Detector/__init__.py
  detectors/detector_api.py
  example.env
  plugins/.gitignore
  plugins/README.md
  plugins/azure_functions/.funcignore
  plugins/azure_functions/.gitignore
  plugins/azure_functions/.prettierrc
  plugins/azure_functions/.vscode/extensions.json
  plugins/azure_functions/.vscode/launch.json
  plugins/azure_functions/.vscode/settings.json
  plugins/azure_functions/.vscode/tasks.json
  plugins/azure_functions/Detector/__init__.py
  plugins/azure_functions/Detector/function.json
  plugins/azure_functions/SpectrogramThumbnails/__init__.py
  plugins/azure_functions/SpectrogramThumbnails/function.json
  plugins/azure_functions/SpectrogramThumbnails/readme.md
  plugins/azure_functions/host.json
  plugins/azure_functions/old_python_snippet.py
  plugins/azure_functions/requirements.txt
  plugins/lowpass_filter/lowpass_filter.py
  plugins/lowpass_filter/requirements.txt
  plugins/markos_detector/markos_detector.py
  plugins/markos_detector/requirements.txt
  plugins/openapi.yaml
  plugins/plugins_api.py
  plugins/plugins_example_call.http
  plugins/requirements.txt
  plugins/simple_detector/requirements.txt
  plugins/simple_detector/simple_detector.py
  plugins/template_plugin/requirements.txt
  plugins/template_plugin/template_plugin.py
Labels: chore

#186 APIClient repo tile added to repobrowser
  .gitignore
  api/database/database.py
  api/database/models.py
  api/handlers/config.py
  api/handlers/datasources.py
  api/handlers/metadata.py
  api/main.py
  api/requirements-test.txt
  api/requirements.txt
  api/tests/test_api.py
  client/src/Components/RepoBrowser/RepoBrowser.tsx
  client/src/Components/RepoBrowser/RepositoryAPITile.tsx
  client/src/Components/RepoBrowser/__tests__/RepoBrowser.test.tsx
  client/src/Components/RepoBrowser/__tests__/setupTests.tsx
  client/src/api/datasource/ApiClient.ts
  client/src/api/datasource/BlobClient.ts
  client/src/api/datasource/DataSourceClient.ts
  client/src/api/datasource/LocalClient.ts
  e2e/README.md
  e2e/__tests__/confirm_API_data_browse.spec.ts
  e2e/playwright.config.ts
Labels: enhancement

#202 Add debugger for front end
  .vscode/launch.json
Labels: chore

#203 Moving files to behave like the new folder structure
  client/src/App.tsx
  client/src/Components/RepoBrowser/SiggenTile.tsx
  client/src/Components/RepoBrowser/ValidatorTile.tsx
  client/src/api/datasource/DataSourceClient.ts
  client/src/api/datasource/__tests__/ApiClient.test.tsx
  client/src/hooks/useIQEngineQueryClient.tsx
  client/src/hooks/useIQEngineRouter.tsx
  client/src/index.tsx
  client/src/pages/About.tsx
  client/src/pages/Plugins.tsx
  client/src/pages/SigMF.tsx
  client/src/pages/signalGenerator/SignalGenerator.tsx
  client/src/pages/signalGenerator/examples/README.md
  client/src/pages/signalGenerator/examples/bpskToneNoise.ts
  client/src/pages/signalGenerator/examples/exampleList.ts
  client/src/pages/signalGenerator/examples/ofdm.ts
Labels: chore

#196 Downloading selections of signal
  client/src/Components/Spectrogram/ScrollBar.tsx
  client/src/Components/Spectrogram/SettingsPane.tsx
  client/src/Components/Spectrogram/Sidebar.tsx
  client/src/Components/Spectrogram/TimeSelector.tsx
Labels: enhancement, feature, don't merge

#208 Fix routing for internal pages
  api/main.py
Labels: bug

#215 Fix button click handling
  client/src/Components/RepoBrowser/RepositoryTile.tsx
Labels: bug

#218 Save meta
  client/src/Components/Metadata/MetaRaw.tsx
  client/src/Components/Metadata/MetaViewer.tsx
  client/src/Components/Metadata/__tests__/MetaRaw.test.tsx
  client/src/Components/Metadata/__tests__/MetaViewer.test.tsx
  client/src/Components/RepoBrowser/__tests__/RepoBrowser.test.tsx
  client/src/Components/Spectrogram/SpectrogramPage.tsx
  client/src/Utils/__tests__/sigmfMetadata.test.ts
  client/src/Utils/sigmfMetadata.ts
  client/src/api/metadata/ApiClient.ts
  client/src/api/metadata/BlobClient.ts
  client/src/api/metadata/LocalClient.ts
  client/src/api/metadata/MetadataClient.ts
  client/src/api/metadata/Queries.ts
  client/src/api/metadata/__tests__/ApiClient.test.tsx
  client/src/mocks/setupTests.tsx
Labels: enhancement

#222 Add language extension
  client/src/Components/Validator/Validator.tsx
Labels: chore

#224 Add install to readme
  e2e/README.md
Labels: documentation

#228 Update staging url
  e2e/playwright-pr.config.ts
Labels: chore

#231 Fix for capture datetime empty
  client/src/Components/Annotation/AnnotationList.tsx
  client/src/Components/Annotation/AnnotationViewer.tsx
  client/src/Components/Annotation/__tests__/AnnotationList.test.tsx
Labels: bug

#226 Adding mouse scroll to the spectrogram
  client/src/Components/Spectrogram/SpectrogramPage.tsx
Labels: enhancement

#232 fix-for-annotations-viewer
  client/src/Components/Annotation/AnnotationList.tsx
  client/src/Components/Annotation/AnnotationViewer.tsx
  client/src/Components/AutoSizeInput/AutoSizeInput.tsx
  client/src/Components/Metadata/MetaRaw.tsx
  client/src/Components/Spectrogram/SpectrogramPage.tsx
Labels: bug

#230 Implement IQ Data API
  .vscode/launch.json
  .vscode/settings.json
  api/database/models.py
  api/handlers/cipher.py
  api/handlers/datasources.py
  api/handlers/iq.py
  api/main.py
  api/requirements-test.txt
  api/requirements.txt
  api/tests/test_api.py
  api/tests/test_data.py
  api/tests/test_iq_api.py
  client/package-lock.json
  client/src/Components/Metadata/__tests__/MetaRaw.test.tsx
  client/src/Components/RepoBrowser/__tests__/RepoBrowser.test.tsx
  client/src/api/datasource/ApiClient.ts
  client/src/api/iqdata/ApiClient.ts
  client/src/api/metadata/ApiClient.ts
  client/src/api/metadata/__tests__/ApiClient.test.tsx
Labels: enhancement

#237 Fix playwright tests
  client/src/Components/RepoBrowser/AzureBlobBrowser.tsx
  client/src/Components/RepoBrowser/SiggenTile.tsx
  client/src/Components/RepoBrowser/ValidatorTile.tsx
  e2e/__tests__/confirm_all_repos.spec.ts
  e2e/__tests__/siggen.spec.ts
Labels: bug

#239 Add feature flags for social links
  client/src/App.tsx
  client/src/Components/Feature/__tests__/Feature.test.tsx
  client/src/__tests__/App.test.tsx
Labels: feature

#243 Github feature flag
  client/src/App.tsx
  client/src/__tests__/App.test.tsx
Labels: feature

#242 Protect data source sas tokens with SecertStr
  api/database/models.py
  api/handlers/cipher.py
Labels: python

#246 Add feature flag env to release ymls
  api/handlers/config.py
  api/tests/test_api.py
Labels: feature

#250 Add feature flag for internal branding
  client/public/internalbrandingeg.jpg
  client/src/App.tsx
  client/src/__tests__/App.test.tsx
Labels: feature

#249 move database warmup to global setup
  .cspell.json
  .dockerignore
  Makefile
  e2e/__tests__/confirm_API_data_browse.spec.ts
  e2e/__tests__/global.setup.ts
  e2e/playwright.config.ts
  e2e/webServer.sh
Labels: bug

#247 Remove envs from release yml
  .github/workflows/docker-pre-release.yml
  .github/workflows/docker-release.yml
Labels: chore

#259 Re-name env variables and remove duplicates
  README.md
  api/database/database.py
  api/handlers/config.py
  api/tests/test_api.py
  client/src/Components/RepoBrowser/RepoBrowser.tsx
  client/src/Components/RepoBrowser/__tests__/RepoBrowser.test.tsx
  client/src/Components/Spectrogram/PluginsPane.tsx
  client/src/__tests__/App.test.tsx
  client/src/api/config/queries.test.tsx
  client/src/api/config/queries.ts
  client/vite.config.ts
  docker-compose.yml
  e2e/webServer.sh
  example.env
  infra/iqengine.json
  infra/main.bicep
  plugins/README.md
Labels: chore

#260 Fix screen location bug on resize
  client/src/Components/Spectrogram/SpectrogramPage.tsx
Labels: bug

#262 Add processors endpoint to API
  api/database/database.py
  api/database/models.py
  api/handlers/processors.py
  api/main.py
  api/tests/test_processors.py
Labels: feature

#263 Add docker and requirements txt changes
  .github/linters/.hadolint.yaml
  .mega-linter.yml
  plugins/Dockerfile
  plugins/src/simple_detector/requirements.txt
Labels: bug

#267 Update readme to include ff
  README.md
Labels: documentation

#264 Add hook processors
  .vscode/settings.json
  api/database/database.py
  api/database/models.py
  api/handlers/plugins.py
  api/handlers/processors.py
  api/importer/__init__.py
  api/importer/all.py
  api/importer/plugins.py
  api/main.py
  api/tests/test_plugins.py
  api/tests/test_processors.py
  client/src/api/Models.ts
  client/src/api/metadata/__tests__/ApiClient.test.tsx
  client/src/api/plugin/Queries.tsx
  client/src/api/plugin/__tests__/Queries.test.tsx
  client/src/hooks/useIQEngineQueryClient.tsx
  client/src/mocks/setupTests.tsx
Labels: enhancement

#248 Update data source API
  api/database/models.py
  api/handlers/cipher.py
  api/handlers/datasources.py
  api/handlers/iq.py
  api/handlers/metadata.py
  api/handlers/urlmapping.py
  api/tests/test_api.py
  client/src/Utils/sigmfMetadata.ts
  client/src/api/datasource/ApiClient.ts
  client/src/api/datasource/__tests__/ApiClient.test.tsx
Labels: enhancement, python

#270 Re-refactor feature flags
  README.md
  client/src/App.tsx
  client/src/Components/Feature/Feature.tsx
  client/src/Components/RepoBrowser/RepoBrowser.tsx
  client/src/__tests__/App.test.tsx
  client/src/api/config/queries.ts
  client/src/hooks/useFeatureFlags.tsx
  client/src/index.tsx
  client/src/mocks/setupTests.tsx
Labels: bug, chore

#268 switch to mongo for tests
  docker-compose-e2e.yml
  e2e/example.env
  e2e/teardown.sh
  e2e/webServer.sh
Labels: chore

#275 Add console logs for adding env variables
  client/src/api/config/queries.ts
  client/src/hooks/useFeatureFlags.tsx
Labels: chore

#271 Adding UI changes for plugin
  client/src/Components/Spectrogram/SpectrogramContext.ts
  client/src/api/Models.ts
  client/src/api/plugin/Queries.tsx
  client/src/api/plugin/__tests__/Queries.test.tsx
  client/src/hooks/useIQEngineRouter.tsx
  client/src/pages/spectrogram/InfoPane.tsx
  client/src/pages/spectrogram/RulerSide.tsx
  client/src/pages/spectrogram/RulerTop.tsx
  client/src/pages/spectrogram/ScrollBar.tsx
  client/src/pages/spectrogram/SettingsPane.tsx
  client/src/pages/spectrogram/Sidebar.tsx
  client/src/pages/spectrogram/SpectrogramPage.tsx
  client/src/pages/spectrogram/TimeSelector.tsx
  client/src/pages/spectrogram/components/FrequencyPlot.tsx
  client/src/pages/spectrogram/components/IQPlot.tsx
  client/src/pages/spectrogram/components/PluginsPane.tsx
  client/src/pages/spectrogram/components/TimePlot.tsx
  client/src/pages/spectrogram/hooks/__tests__/useGetPluginsComponents.test.tsx
  client/src/pages/spectrogram/hooks/useGetPluginsComponents.tsx
Labels: enhancement

#278 Adding fix to invalid plugins config
  README.md
  api/handlers/config.py
  api/tests/test_api.py
  client/src/Components/RepoBrowser/__tests__/RepoBrowser.test.tsx
  client/src/api/config/queries.test.tsx
  client/src/api/config/queries.ts
  client/src/pages/spectrogram/components/PluginsPane.tsx
  docker-compose-e2e.yml
  docker-compose.yml
  plugins/README.md
Labels: bug

#279 Do not allow insecure
  infra/containerapp.bicep
  infra/iqengine.json
Labels: chore

#283 create trivial plugin
  .vscode/launch.json
  api/importer/plugins.py
  client/src/pages/spectrogram/components/PluginsPane.tsx
  plugins/src/wav_out/sheep.wav
  plugins/src/wav_out/wav_out.py
Labels: feature

#282 Make plugins load fron environment
  .vscode/launch.json
  api/importer/all.py
  api/importer/plugins.py
  api/main.py
  api/tests/test_importer.py
Labels: bug

#285 Run pw tests on pr
  .github/workflows/run_playwright_tests.yml
  e2e/README.md
  e2e/__tests__/confirm_API_data_browse.spec.ts
  e2e/playwright-pr.config.ts
Labels: enhancement

#289 Add check for metadata
  e2e/__tests__/confirm_gnuradio.spec.ts
Labels: chore

#284 Simple query api
  api/handlers/metadata.py
  api/tests/test_data.py
  api/tests/test_query_api.py
Labels: enhancement, python
