Repository IQEngine/IQEngine, pull requests merged in 2023-08, with the labels that each got.

#409 Global metadata
  client/src/pages/recording-view/components/__tests__/global-properties.test.tsx
  client/src/pages/recording-view/components/__tests__/meta-raw.test.tsx
  client/src/pages/recording-view/components/__tests__/meta-viewer.test.tsx
  client/src/pages/recording-view/components/global-properties.tsx
  client/src/pages/recording-view/components/meta-raw.tsx
  client/src/pages/recording-view/components/meta-viewer.tsx
  client/src/pages/recording-view/recording-view.tsx
Labels: chore

#410 Annotations
  client/src/pages/recording-view/components/annotation/__tests__/actions.test.tsx
  client/src/pages/recording-view/components/annotation/__tests__/annotation-list.test.meta.json
  client/src/pages/recording-view/components/annotation/__tests__/annotation-list.test.tsx
  client/src/pages/recording-view/components/annotation/actions.tsx
  client/src/pages/recording-view/components/annotation/annotation-list.tsx
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
  client/src/pages/recording-view/recording-view.tsx
Labels: chore

#420 Correcting annotation viewer
  client/src/hooks/use-query-client.tsx
  client/src/pages/recording-view/components/annotation/annotation-list.tsx
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
  client/src/pages/recording-view/components/scroll-bar.tsx
  client/src/pages/recording-view/hooks/use-spectrogram-context.tsx
  client/src/pages/recording-view/recording-view.tsx
Labels: chore

#422 Add resize to recording view
  client/src/pages/recording-view/recording-view.tsx
Labels: chore

#419 Send annotation to plugin
  client/src/pages/spectrogram/components/PluginsPane.tsx
  client/src/pages/spectrogram/sidebar.tsx
  client/src/pages/spectrogram/spectrogram-page.tsx
Labels: feature

#425 Add annotation to plugin for recording view
  client/src/pages/recording-view/components/plugins-pane.tsx
  client/src/pages/spectrogram/components/PluginsPane.tsx
Labels: chore

#426 fix scrolling after end of file bug
  client/src/pages/recording-view/components/scroll-bar.tsx
  client/src/pages/recording-view/recording-view.tsx
Labels: bug

#428 Adding list for downloaded tiles
  .vscode/launch.json
  client/src/api/iqdata/Queries.ts
  client/src/api/metadata/queries.ts
  client/src/pages/recording-view/components/scroll-bar.tsx
  client/src/pages/recording-view/hooks/__tests__/use-spectrogram.test.tsx
  client/src/pages/recording-view/hooks/use-spectrogram.tsx
  client/src/utils/constants.ts
Labels: chore

#436 Small fix for the size of plugins
  client/src/pages/recording-view/components/settings-pane.tsx
Labels: chore

#451 added new data type
  api/rf/samples.py
  api/tests/test_samples.py
  client/src/utils/fetch-more-data-source.ts
Labels: chore

#450 Fix Add Annotation
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
Labels: bug

#452 Add users and their security groups
  client/src/pages/admin/__tests__/admin-unauthorised.test.tsx
  client/src/pages/admin/__tests__/admin.test.tsx
  client/src/pages/admin/admin.tsx
  client/src/pages/admin/pages/__tests__/users.test.tsx
  client/src/pages/admin/pages/users.tsx
  client/src/pages/recording-view/components/__tests__/meta-raw-unauthorised.test.tsx
  client/src/pages/recording-view/components/__tests__/meta-raw.test.tsx
  client/src/pages/recording-view/components/meta-raw.tsx
Labels: feature

#461 User administration to utilise backend
  api/graph/graph_client.py
  api/handlers/users.py
  api/main.py
  api/requirements.txt
  api/tests/test_api.py
  client/src/api/Models.ts
  client/src/api/users/__tests__/queries.test.tsx
  client/src/api/users/queries.tsx
  client/src/hooks/use-access-token.tsx
  client/src/pages/admin/pages/__tests__/users.test.tsx
  client/src/pages/admin/pages/users.tsx
Labels: don't merge

#462 Fix cursor error
  client/src/pages/recording-view/components/plugins-pane.tsx
Labels: bug

#460 Handle backend cancellation
  api/handlers/iq.py
  api/helpers/apidisconnect.py
  api/main.py
Labels: chore

#429 Local File implementation of getIQDataBlocks
  client/src/api/iqdata/LocalClient.ts
  client/src/api/iqdata/__tests__/LocalClient.test.tsx
Labels: feature

#501 Bumped as many deps as possible
  .github/linters/.yamllint.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/docker-plugin-base-image.yml
  .github/workflows/docker-pre-release.yml
  .github/workflows/docker-release.yml
  .github/workflows/linter.yml
  .github/workflows/periodic_test_of_prod.yml
  .github/workflows/periodic_test_of_staging.yml
  .github/workflows/run_api_tests.yml
  .github/workflows/run_client_tests.yml
  .github/workflows/run_playwright_tests.yml
  .github/workflows/scorecard.yml
  Dockerfile
  Makefile
  api/requirements.txt
  client/package-lock.json
  client/package.json
  e2e/package-lock.json
  e2e/package.json
  plugins/src/azure_functions/.funcignore
  plugins/src/azure_functions/.gitignore
  plugins/src/azure_functions/.prettierrc
  plugins/src/azure_functions/.vscode/extensions.json
  plugins/src/azure_functions/.vscode/launch.json
  plugins/src/azure_functions/.vscode/settings.json
  plugins/src/azure_functions/.vscode/tasks.json
  plugins/src/azure_functions/Detector/__init__.py
  plugins/src/azure_functions/Detector/function.json
  plugins/src/azure_functions/SpectrogramThumbnails/__init__.py
  plugins/src/azure_functions/SpectrogramThumbnails/function.json
  plugins/src/azure_functions/SpectrogramThumbnails/readme.md
  plugins/src/azure_functions/host.json
  plugins/src/azure_functions/old_python_snippet.py
  plugins/src/azure_functions/requirements.txt
  plugins/src/lowpass_filter/requirements.txt
  plugins/src/markos_detector/requirements.txt
  plugins/src/requirements.txt
  plugins/src/simple_detector/requirements.txt
  plugins/src/template_plugin/requirements.txt
  tools/metadata_loader/requirements.txt
  tools/metadata_loader/requirements_tests.txt
  tools/pmtiles/requirements.txt
Labels: chore

#518 Convert from AngelSDR's SDRIQ format to SigMF
  .gitignore
  client/src/pages/repo-browser/local-file-browser.tsx
  tools/sdriq2sigmf/README.md
  tools/sdriq2sigmf/requirements.txt
  tools/sdriq2sigmf/sdriq2sigmf.py
Labels: feature

#531 Add file types support to plugins
  .mega-linter.yml
  client/src/pages/recording-view/components/plugins-pane.tsx
  plugins/src/samples.py
Labels: chore, feature

#427 Access control for data sources
  api/database/datasource_repo.py
  api/database/metadata_repo.py
  api/database/models.py
  api/handlers/datasources.py
  api/handlers/iq.py
  api/handlers/metadata.py
  api/handlers/plugins.py
  api/helpers/authorization.py
  api/helpers/datasource_access.py
  api/importer/datasource.py
  api/tests/conftest.py
  api/tests/test_api.py
  api/tests/test_data.py
  api/tests/test_iq_api.py
  api/tests/test_rbac.py
  client/src/api/datasource/api-client.ts
  client/src/api/datasource/datasource-client-factory.ts
  client/src/app.tsx
  client/src/auth/hooks/use-auth-provider.tsx
  tools/metadata_loader/main.py
Labels: feature, python

#517 Ignore the models dir when finding available plugins
  plugins/src/plugins_api.py
Labels: chore

#552 Add select plugin option at top of plugins pane
  client/src/pages/recording-view/components/plugins-pane.tsx
Labels: bug

#554 Fix signup page link spanning the whole width of page
  client/src/app.tsx
Labels: bug

#574 🐛 fix bug on local storage
  client/src/api/metadata/local-client.ts
  client/src/api/metadata/queries.ts
  client/src/pages/repo-browser/local-file-browser.tsx
Labels: bug

#564 🔧 Adding a new minimap
  api/blob/azure_client.py
  api/handlers/iq.py
  api/handlers/metadata.py
  api/helpers/urlmapping.py
  api/requirements.txt
  api/tests/test_iq_api.py
  api/tests/test_metadata.py
  client/src/api/datasource/api-client.ts
  client/src/api/iqdata/ApiClient.ts
  client/src/api/iqdata/BlobClient.ts
  client/src/api/iqdata/IQDataClient.ts
  client/src/api/iqdata/LocalClient.ts
  client/src/api/iqdata/Queries.ts
  client/src/pages/recording-view/components/scroll-bar.tsx
Labels: feature

#576 Add annotation improvements
  client/src/pages/recording-view/components/annotation/__tests__/actions.test.tsx
  client/src/pages/recording-view/components/annotation/actions.tsx
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
  client/src/utils/__tests__/sigmfMetadata.test.ts
  client/src/utils/sigmfMetadata.ts
Labels: bug

#577 🚧 Adding a limitation of around 1MB
  client/src/api/iqdata/Queries.ts
  client/src/api/utils/Auth-Utils.ts
Labels: bug, chore

#561 Add SAS fetch
  api/importer/datasource.py
  api/tests/test_importer.py
  client/src/api/Models.ts
  client/src/api/datasource/api-client.ts
  client/src/api/datasource/blob-client.ts
  client/src/api/datasource/datasource-client.ts
  client/src/api/datasource/local-client.ts
  client/src/api/datasource/queries.ts
  client/src/pages/admin/pages/add-data-source.tsx
  client/src/pages/recording-view/components/plugins-pane.tsx
  e2e/package-lock.json
  e2e/package.json
Labels: bug

#579 Fix width of taps menu
  client/src/pages/recording-view/components/settings-pane.tsx
Labels: bug

#581 Change frequency selection
  client/src/pages/metadata-query/__tests__/band-selection.test.tsx
  client/src/pages/metadata-query/__tests__/band.test.tsx
  client/src/pages/metadata-query/freq-query.tsx
Labels: bug

#599 Fix the bug for when unable to query on freq page.
  client/src/pages/metadata-query/__tests__/freq-query.test.tsx
  client/src/pages/metadata-query/freq-query.tsx
Labels: bug

#605 Fix landing page bug where page is displaying empty
  client/src/pages/landing-page/landing-page.tsx
Labels: bug

#606 OpenQuery frontend
  .vscode/settings.json
  client/src/api/Models.ts
  client/src/api/metadata/api-client.ts
  client/src/api/metadata/blob-client.ts
  client/src/api/metadata/local-client.ts
  client/src/api/metadata/metadata-client.ts
  client/src/api/metadata/queries.ts
  client/src/hooks/use-query-client.tsx
  client/src/hooks/use-router.tsx
  client/src/pages/repo-browser/repo-browser.tsx
  client/src/pages/repo-browser/smart-query-tile.tsx
  client/src/pages/smart-query/smart-query.tsx
Labels: feature

#608 Correcting visuals smart query
  client/src/pages/smart-query/smart-query.tsx
Labels: bug

#611 Fix local cloud pointer and annotations overflow
  client/src/pages/recording-view/components/annotation/annotation-viewer.tsx
  client/src/pages/recording-view/components/plugins-pane.tsx
Labels: bug
